### ISSUE TITLE
Docs Todos

### ISSUE THREAD

**Issue by gamarin2** [cosmos/advocates#3]
This issue is a list of the major documentation ToDos for each project.

## Cosmos SDK

- [x] Write Scaffold Guide (`using-the-sdk` section)
- [ ] Write follow-up "Adding Modules" guide (`using-the-sdk` section)
- [x] Finish simulation docs
- [ ] Update module specs (e.g. `gov`)
- [ ] Write migration docs (`using-the-sdk` section)
- [ ] Improve ocaps docs 
- [ ] Tokens docs (denom, bech32 prefixes, cointype)
- [ ] Proof of Stake overview doc
- [ ] params concept doc
- [ ] Write "Validators" basic concept docs
- [ ] Validator set changes overview doc
- [ ] Improve `context`  
- [ ] Write "deploying your chain" doc
- [ ] Write "upgrading your chain" doc
- [ ] Turn "Store" doc into "Store" section, with one doc per store type
- [ ] add example of how people could use their own key types

## Tutorials

- [ ] Upgrade hello-chain
- [x] New landing page - allinbits/design/issues/265
- [ ] Add IBC tutorial (potentially as section of nameservice)
- [ ] Typescript basic client tutorial (probably an SPA client of nameservice)

## Gaia 

- [x] Update to new theme
- [ ] Read through of all docs and update/improve what needs to be
- [ ] Rework landing page - related to allinbits/design/issues/182
- [x] Rethink role of swagger docs (is it a gaia rpc endpoints list, or a generic cosmos sdk rpc endpoints list)
- [ ] Add delegator intro section (staking section?)
- [ ] Add governance section
- [x] add section on pruning

## IBC

- [ ] Write concept docs for the main IBC concepts (Connection, channel, handhsake, ...)
- [ ] Write SDK IBC implementation guide 
- [ ] Move generic docs (spec, concept docs, ...) to a repo outside of `cosmos` github org (ICF?)

## Tendermint 

- [ ] New landing page - allinbits/design/issues/266
- [x] Update organisation/architecture of the docs 
- [ ] Read through of all docs and update/improve what needs to be

**Comment by tac0turtle** [comment]
a doc on how to repurpose the ledger app for different chains is needed.
